---
title: "MC_paper2_decontam_phyloseq_import"
author: "Zeya Zhengyao Xue"
date: "January 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This file follows the analysis in QIIME2, which imports mapping file, feature table,
taxonomy and tree as a 4-component phyloseq object. 

## Setting up packages and working directory 
```{r}
library(decontam);packageVersion("decontam")
library(phyloseq);packageVersion("phyloseq")
library(ggplot2);packageVersion("ggplot2")
library(reshape2);packageVersion("reshape2")
library(cowplot);packageVersion("cowplot")
library(dplyr);packageVersion("dplyr")

path <- "G:/My Drive/UC_Davis/Marco_lab/milk_microbiota/Mock_community/MC_paper2_QIIME2/"
```

## Import QIIME2 output and make phyloseq object
```{r}
# Transpose the QIIME2 output in excel
# For the theoretical values, I can adjust its absolute reads to suit data set by
# changing values in the feature table
SeqTab <- read.table(file.path(path,"feature-table-mc2.txt"), header = TRUE, stringsAsFactors = FALSE)
colnames(SeqTab) <- gsub("X","",colnames(SeqTab))
row.names(SeqTab) <- SeqTab$OTUID
SeqTab <- SeqTab[,-1]
SeqTab <- as.matrix.data.frame(SeqTab)


```


