---
title: "Lacto_depletion_analysis"
author: "Zeya Zhengyao Xue"
date: "March 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting up packages and working directory 
```{r}
library(ggplot2)
library(reshape2)
library(plyr)
library(dplyr)

path <- "G:/My Drive/UC_Davis/Marco_lab/milk_microbiota/Depletion_Abundant_sequences/Agilent_SureSelect/sequencing/"
```

```{r}
# qPCR results of all samples 
qPCR.abun <- read.csv(file.path(path, "qPCR_abudance.csv"))
qPCR.abunm <- melt(qPCR.abun, id.vars = c("ID","SampleType","SampleName"),
                   na.rm = TRUE)
qPCR.abunm$SampleType <- factor(qPCR.abunm$SampleType, 
                                levels = c("Expected","Mix","Fragmentation",
                                           "Hybridization","Wash1","Wash2","Beads"))
qPCR.abunm$SampleName <- factor(qPCR.abunm$SampleName, 
                                levels = c(paste0("Mix",c(1:8)), "4045", "4046", 
                                           "4068", "4069","3638","3944"))

pdf(file.path(path, "figs/relative_stacked_bar_4SamName.pdf"), w = 8, h = 8)
ggplot(subset(qPCR.abunm, SampleType %in% c("Mix","Hybridization","Wash1","Wash2")), 
       aes(x = SampleType, y = value, fill = variable))+
  facet_wrap(SampleName ~ ., scales = "fixed", ncol = 3)+
  geom_bar(stat = "identity", position = "fill")+
  theme_bw(base_size = 16)
dev.off()

# qPCR results of a subset of Hyb, W1 and W2 samples
qPCR.sub <- read.csv(file.path(path, "qPCR_abudance_subset.csv"))
qPCR.subm <- melt(qPCR.sub, id.vars = c("ID","SampleType","SampleName","Treatment"),
                  na.rm = TRUE)
qPCR.subm$log <- log10(qPCR.subm$value)
qPCR.subm$Treatment <- factor(qPCR.subm$Treatment, levels = c("Untreated","Treated"))
qPCR.subm$SampleName <- factor(qPCR.subm$SampleName, 
                               levels = c(paste0("Mix",c(1:8)), "4045", "4046", 
                                          "4068", "4069","3638","3944"))

pdf(file.path(path, "figs/relative_stacked_bar_2treatmnt.pdf"), w = 6, h = 8)
ggplot(subset(qPCR.subm, variable %in% c("Lactococcus","Pseudomonas","Lactobacillus")),
       aes(x = Treatment, y = value, fill = variable))+
  facet_wrap(SampleName ~ ., scales = "fixed", ncol = 3)+
  geom_bar(stat = "identity", position = "fill")+
  theme_bw(base_size = 16)
dev.off()

pdf(file.path(path, "figs/abs_abun_dodged_bar_2treatmnt.pdf"), w = 8, h = 5)
ggplot(subset(qPCR.subm, variable %in% c("Lactococcus","Pseudomonas","Lactobacillus")),
       aes(x = SampleName, y = log, fill = Treatment))+
  facet_wrap(variable ~ ., scales = "free")+
  geom_bar(stat = "identity", position = "dodge")+
  theme_bw(base_size = 16)
dev.off()

pdf(file.path(path, "figs/relative_dodged_bar_2treatmnt.pdf"), w = 8, h = 6)
ggplot(subset(qPCR.subm, variable %in% c("Lactococcus_prop",
                                         "Pseudomonas_prop",
                                         "Lactobacillus_prop")),
       aes(x = SampleName, y = value, fill = Treatment))+
  facet_wrap(variable ~ ., scales = "fixed", ncol = 1)+
  geom_bar(stat = "identity", position = "dodge")+
  theme_bw(base_size = 16)
dev.off()



# qPCR results of a subset of Hyb, W1 and W2 samples and 
# only successful samples from run 1-3 (run 4 fail, run1 mix4 fail)
qPCR.succ <- read.csv(file.path(path, "qPCR_abudance_subset_run1-3.csv"))
qPCR.succm <- melt(qPCR.succ, id.vars = c("ID","SampleType","SampleName","Treatment"),
                   na.rm = TRUE)
qPCR.succm$Treatment <- factor(qPCR.succm$Treatment, levels = c("Untreated","Treated"))
qPCR.succm$SampleName <- factor(qPCR.succm$SampleName, 
                                levels = c(paste0("Mix",c(1:8)), "4045", "4046", 
                                           "4068", "4069","3638","3944"))

pdf(file.path(path, "figs/relative_dodged_bar_2treatmnt_run1-3.pdf"), w = 5, h = 6)
ggplot(subset(qPCR.succm, variable %in% c("Lactococcus_prop",
                                          "Pseudomonas_prop",
                                          "Lactobacillus_prop")),
       aes(x = SampleName, y = value, fill = Treatment))+
  facet_wrap(variable ~ ., scales = "fixed", ncol = 1)+
  geom_bar(stat = "identity", position = "dodge")+
  theme_bw(base_size = 16)
dev.off()

```


